import { Injectable } from '@nestjs/common';
import { DatabaseService } from '../database/database.service';
import { StorageService } from './storage.service';
import { isNotConfigured } from '../common/not-configured.exception';

/**
 * PDF ASSETS IN R2 (docs/dev/57).
 *
 * Every generated business PDF (certificate / report card / GST invoice / quotation / fee
 * receipt / refund voucher / purchase order) is persisted to Cloudflare R2 and indexed in
 * `generated_document` — the PDF bytes NEVER touch the server disk and are NEVER stored as a
 * DB blob; only the R2 key lives in the DB. Idempotent per (kind, ref_id): a reissue / revise
 * overwrites the same key.
 *
 * When R2 is not configured this degrades cleanly — `persist` is a no-op that returns null, so
 * the on-demand PDF endpoints keep working exactly as before (streaming freshly-generated bytes).
 */
@Injectable()
export class PdfAssetService {
  constructor(
    private readonly db: DatabaseService,
    private readonly storage: StorageService,
  ) {}

  /** Upload the PDF to R2 + upsert the index row. Returns the key, or null if R2 is not set. */
  async persist(kind: string, refId: number, docNo: string | null, buffer: Buffer, orgId?: number | null): Promise<string | null> {
    // Best-effort + resilient: R2 storage must NEVER break the core issue/download flow.
    // Not-configured returns null silently; a transient R2/DB error is swallowed (the download
    // path re-persists next time). Nothing sensitive is ever logged.
    if (!(await this.storage.isConfigured())) return null;
    const key = this.storage.pdfKey(kind, docNo || `${kind}-${refId}`);
    try {
      await this.storage.putObject(key, buffer, 'application/pdf');
      await this.db.query(
        `INSERT INTO generated_document (org_id, kind, ref_id, doc_no, r2_key, content_type, size_bytes, updated_at)
         VALUES ($1,$2,$3,$4,$5,'application/pdf',$6, now())
         ON CONFLICT (kind, ref_id)
         DO UPDATE SET r2_key = EXCLUDED.r2_key, doc_no = EXCLUDED.doc_no, size_bytes = EXCLUDED.size_bytes, updated_at = now()`,
        [orgId ?? null, kind, refId, docNo ?? null, key, buffer.length]);
      return key;
    } catch (e) {
      if (isNotConfigured(e)) return null;
      return null;
    }
  }

  /** The stored R2 key for a (kind, ref_id), or null. */
  async keyOf(kind: string, refId: number): Promise<string | null> {
    const r = await this.db.one<{ r2_key: string }>(
      `SELECT r2_key FROM generated_document WHERE kind = $1 AND ref_id = $2`, [kind, refId]);
    return r?.r2_key ?? null;
  }

  /** A short-lived presigned download URL for a (kind, ref_id), or null if not stored / R2 off. */
  async presignedUrl(kind: string, refId: number, downloadName?: string): Promise<string | null> {
    const key = await this.keyOf(kind, refId);
    if (!key) return null;
    try { return await this.storage.presignGet(key, 300, downloadName); }
    catch (e) { if (isNotConfigured(e)) return null; throw e; }
  }
}
